name: semantic-release

on:
  push:
    branches:
    - main

jobs:
  semantic-release:
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}
        with:

          extends: |
            conventional-changelog-conventionalcommits
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
            @semantic-release/commit-analyzer
            @semantic-release/exec