name: semantic-release-dry-run

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["python-tests"]
    types:
      - completed

jobs:
  semantic-release-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release dry run
        id: dry-release
        run: |
          # Trick semantic-release into thinking we're not in a CI environment
          unset GITHUB_ACTIONS
          unset GITHUB_EVENT_NAME

          npx semantic-release --dry-run --no-ci --branches $GITHUB_HEAD_REF
