name: semantic-release-dry-run

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["python-tests"]
    types:
      - completed

jobs:
  semantic-release-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Semantic Release dry run
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          ci: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
