name: semantic-release-dry-run

on:
  pull_request:
    branches:
      - main

jobs:
  semantic-release-dry-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          extends: |
            conventional-changelog-conventionalcommits
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
            @semantic-release/commit-analyzer
            @semantic-release/exec

      - name: Get new release version or assign current
        run: |
          if [ "${{ steps.release.outputs.new_release_version }}" != "" ]; then
            echo "release_version=v${{ steps.release.outputs.new_release_version }}" >> $GITHUB_ENV
          elif [ "$(git tag --points-at ${{ steps.short-sha.outputs.short-sha }})" != "" ]; then
            echo "release_version=$(git tag --points-at ${{ steps.short-sha.outputs.short-sha }})" >> $GITHUB_ENV
          else
            echo "release_version=$(git describe --always --tags)" >> $GITHUB_ENV
          fi