name: semantic-release-dry-run

on:
  pull_request:
    branches:
      - main

jobs:
  semantic-release-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
          extends: |
            conventional-changelog-conventionalcommits
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
            @semantic-release/commit-analyzer
            @semantic-release/exec
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
